environment: development

# Skate environment
chain_id: 5051
skate_wss_rpc: wss://nollie-rpc.skatechain.org/socket
skate_http_rpc: https://nollie-rpc.skatechain.org

skate_app: 0x2968C1663B41Cc633540148c679f43136a4644Fc

# HoleSky environments
skate_avs: 0x2a0D46ED3D9D13F6a9b5B0D3274675143c803071

# EVM RPC
holesky_http_rpc: https://holesky.drpc.org
holesky_wss_rpc: wss://holesky.drpc.org
# Other chain RPCs
# ARbitrum, mantle, ...

# Process (relayer/operator) signer address
signer: 0x786775c9ecB916bd7f5a59c150491871fCfCEe86

# Strategies
wsETH_strategy: 0x786775c9ecB916bd7f5a59c150491871fCfCEe86

# avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
eigen_metrics_ip_port_address: localhost:9090
enable_metrics: true
node_api_ip_port_address: localhost:9010
enable_node_api: true
